import type { StoreEntry } from "../lib/storeCatalog";
import { StoreImage } from "./StoreImage";

const labels: Record<string, string> = { psvita: "PS Vita", psp: "PSP", wiiu: "Wii U" };
const platformName = (platform: string) => labels[platform] || platform.toUpperCase();
const count = (value?: number | null) => value == null ? "Sin contador publicado" : `${new Intl.NumberFormat("es").format(value)} descargas registradas`;

export function Trending({ entries, select }: { entries: StoreEntry[]; select: (entry: StoreEntry) => void }) {
  const ranked = entries.filter(entry => entry.popularity != null).sort((a, b) => (b.popularity ?? 0) - (a.popularity ?? 0));
  const platforms = ["3ds", "wii", "wiiu", "switch", "psvita", "psp", "ps4", "ps5"];
  return <div className="space-y-5"><section className="glass rounded-xl p-4"><h2 className="text-sm font-semibold">Más descargados con métrica de la fuente</h2><p className="mt-1 text-xs text-[var(--color-muted)]">Solo se muestran cifras publicadas por el repositorio. Los payloads de PS5 sin contador se mantienen en las novedades por fecha.</p><div className="mt-3 grid gap-2 md:grid-cols-2">{ranked.slice(0, 12).map((entry, index) => <button key={entry.id} onClick={() => select(entry)} className="flex items-center gap-3 rounded-lg p-2 text-left hover:bg-white/5"><span className="w-5 text-center text-xs text-[var(--accent)]">{index + 1}</span><StoreImage url={entry.icon_url} name={entry.name} className="h-10 w-10" /><span className="min-w-0"><span className="block truncate text-xs font-medium">{entry.name}</span><span className="text-[0.65rem] text-[var(--color-muted)]">{entry.platforms.map(platformName).join(" · ")} · {count(entry.popularity)}</span></span></button>)}</div></section><div className="grid gap-4 lg:grid-cols-2">{platforms.map(platform => { const list = ranked.filter(entry => entry.platforms.includes(platform)).slice(0, 5); return <section key={platform} className="glass rounded-xl p-4"><h2 className="text-sm font-semibold">Populares en {platformName(platform)}</h2>{list.length ? list.map(entry => <button key={entry.id} onClick={() => select(entry)} className="mt-2 flex w-full items-center gap-3 rounded-lg p-2 text-left hover:bg-white/5"><StoreImage url={entry.icon_url} name={entry.name} className="h-9 w-9" /><span className="min-w-0"><span className="block truncate text-xs">{entry.name}</span><span className="text-[0.65rem] text-[var(--color-muted)]">{count(entry.popularity)}</span></span></button>) : <p className="mt-2 text-xs text-[var(--color-muted)]">La fuente no publica un contador para esta consola.</p>}</section>})}</div></div>;
}
