<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>romforge-prospero-bridge</AssemblyName>
    <RootNamespace>RomForge.ProsperoBridge</RootNamespace>
    <Version>1.1.0</Version>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="vendor/**/*.cs" />
    <ProjectReference Include="vendor/LibProsperoPKG-src/src/LibProsperoPkg/LibProsperoPkg.csproj" />
  </ItemGroup>
</Project>
